default: true

# unordered-list-indent (default: 2)
MD007:
  indent: 4

# MD013: line-length (default: 80)
MD013: false

# MD025: single-title (allow title in frontmatter)
MD025:
  front_matter_title: ''

# no-inline-html (allow only AutoCatalog)
MD033:
  allowed_elements:
    - AutoCatalog
